### ISSUE TITLE
No longer compatible with Angular 4

### ISSUE THREAD

**Issue by builtbyjay** [sollenne/angular-fittext#12]
Hello!

First of all, great project and thank you for open-sourcing it. I'm having trouble using your module within an Angular 4.4.x project. I can see that you updated it recently to be compatible with Angular 5 but this seems this has broken support for 4. Was this intentional?

Here is my ugly console output when trying to compile:

```
WARNING in ./node_modules/angular-fittext/node_modules/@angular/core/esm5/core.js
6439:15-36 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (/Users/jayvincent/Sites/my-angular4-project/node_modules/webpack/lib/dependencies/ImportContextDependency.js:28:4)
    at Compilation.reportDependencyErrorsAndWarnings (/Users/jayvincent/Sites/my-angular4-project/node_modules/webpack/lib/Compilation.js:677:24)
    at Compilation.finish (/Users/jayvincent/Sites/my-angular4-project/node_modules/webpack/lib/Compilation.js:535:9)
    at applyPluginsParallel.err (/Users/jayvincent/Sites/my-angular4-project/node_modules/webpack/lib/Compiler.js:512:17)
    at /Users/jayvincent/Sites/my-angular4-project/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/Users/jayvincent/Sites/my-angular4-project/node_modules/webpack/lib/Compilation.js:481:11)
    at processModuleDependencies.err (/Users/jayvincent/Sites/my-angular4-project/node_modules/webpack/lib/Compilation.js:452:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

WARNING in ./node_modules/angular-fittext/node_modules/@angular/core/esm5/core.js
6459:15-102 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (/Users/jayvincent/Sites/my-angular4-project/node_modules/webpack/lib/dependencies/ImportContextDependency.js:28:4)
    at Compilation.reportDependencyErrorsAndWarnings (/Users/jayvincent/Sites/my-angular4-project/node_modules/webpack/lib/Compilation.js:677:24)
    at Compilation.finish (/Users/jayvincent/Sites/my-angular4-project/node_modules/webpack/lib/Compilation.js:535:9)
    at applyPluginsParallel.err (/Users/jayvincent/Sites/my-angular4-project/node_modules/webpack/lib/Compiler.js:512:17)
    at /Users/jayvincent/Sites/my-angular4-project/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/Users/jayvincent/Sites/my-angular4-project/node_modules/webpack/lib/Compilation.js:481:11)
    at processModuleDependencies.err (/Users/jayvincent/Sites/my-angular4-project/node_modules/webpack/lib/Compilation.js:452:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

ERROR in Metadata version mismatch for module /Users/jayvincent/Sites/my-angular4-project/node_modules/angular-fittext/node_modules/@angular/core/core.d.ts, found version 4, expected 3, resolving symbol AngularFittextModule in /Users/jayvincent/Sites/my-angular4-project/node_modules/angular-fittext/angular-fittext.d.ts, resolving symbol AngularFittextModule in /Users/jayvincent/Sites/my-angular4-project/node_modules/angular-fittext/angular-fittext.d.ts

webpack: Failed to compile.
```

**Comment by sollenne** [comment]
it wasn't intentional, But I can try to troubleshoot the problem with you. What version of angular-fittext are you using? Is there any reason why you can't update to the latest angular in your codebase? I'll give it a shot on 4.4

**Comment by builtbyjay** [comment]
Very kind of you, but no need to troubleshoot :) I tried with the latest version and 1.0.6 (the last version before you upgraded to 5) - I was able to get 1.0.6 working.

I have seen in some projects the required angular modules/versions being specified as peerDependencies, and the modules/versions used in development as devDependencies. By doing this, you can be more flexible with the compatibility of the module when it's included in other projects. For example: https://github.com/urish/angular2-moment/blob/master/package.json#L91

**Comment by sollenne** [comment]
I really wish peerDependencies worked like that. That's just to say that those packages MUST be installed alongside your package in order for this package to work. so `moment-timezone` obviously requires `moment.js` etc. It is a good idea to add this to my project so that when you install, you would get a warning to tell you that you needed at least angular 5. 

Your issue looks like a webpack issue. That's about as far as I got.

**Comment by sollenne** [comment]
@builtbyjay. I just published a release that removed the strict dependency for angular 5+. You can now use it in your app. Thanks for bringing this to my attention.
